# Generated by Django 5.1.7 on 2025-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='profile_images/'),
        ),
    ]
